# content of: tox.ini , put in same dir as setup.py
[tox]
# python3 interpreter of the user.
envlist = py3

[testenv]
# install pytest in the virtualenv where commands will be executed
deps = pytest
       coverage
       parameterized
commands =
    #pytest test/test_building.py
    #pytest test/test_extraction.py
    # pytest test/test_keras # too expensive, should be checked locally when changes are made to the workflow
    pytest test/test_running.py

[flake8]
max-line-length = 88
select = C,E,F,W,B,B950
extend-ignore = E203, E501, W503, W605, E741